// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: identity/message/message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserMailNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	TextContent   string                 `protobuf:"bytes,3,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	HtmlContent   string                 `protobuf:"bytes,4,opt,name=html_content,json=htmlContent,proto3" json:"html_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMailNotification) Reset() {
	*x = UserMailNotification{}
	mi := &file_identity_message_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMailNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMailNotification) ProtoMessage() {}

func (x *UserMailNotification) ProtoReflect() protoreflect.Message {
	mi := &file_identity_message_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMailNotification.ProtoReflect.Descriptor instead.
func (*UserMailNotification) Descriptor() ([]byte, []int) {
	return file_identity_message_message_proto_rawDescGZIP(), []int{0}
}

func (x *UserMailNotification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserMailNotification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UserMailNotification) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *UserMailNotification) GetHtmlContent() string {
	if x != nil {
		return x.HtmlContent
	}
	return ""
}

var File_identity_message_message_proto protoreflect.FileDescriptor

const file_identity_message_message_proto_rawDesc = "" +
	"\n" +
	"\x1eidentity/message/message.proto\x12\amessage\"\x8b\x01\n" +
	"\x14UserMailNotification\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\ftext_content\x18\x03 \x01(\tR\vtextContent\x12!\n" +
	"\fhtml_content\x18\x04 \x01(\tR\vhtmlContentBAZ?github.com/chise0904/golang_template/proto/pkg/identity/messageb\x06proto3"

var (
	file_identity_message_message_proto_rawDescOnce sync.Once
	file_identity_message_message_proto_rawDescData []byte
)

func file_identity_message_message_proto_rawDescGZIP() []byte {
	file_identity_message_message_proto_rawDescOnce.Do(func() {
		file_identity_message_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_message_message_proto_rawDesc), len(file_identity_message_message_proto_rawDesc)))
	})
	return file_identity_message_message_proto_rawDescData
}

var file_identity_message_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_identity_message_message_proto_goTypes = []any{
	(*UserMailNotification)(nil), // 0: message.UserMailNotification
}
var file_identity_message_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_identity_message_message_proto_init() }
func file_identity_message_message_proto_init() {
	if File_identity_message_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_message_message_proto_rawDesc), len(file_identity_message_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_identity_message_message_proto_goTypes,
		DependencyIndexes: file_identity_message_message_proto_depIdxs,
		MessageInfos:      file_identity_message_message_proto_msgTypes,
	}.Build()
	File_identity_message_message_proto = out.File
	file_identity_message_message_proto_goTypes = nil
	file_identity_message_message_proto_depIdxs = nil
}
