// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: identity/identity.proto

package identity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	common "github.com/chise0904/golang_template/proto/pkg/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountType int32

const (
	AccountType_AccountType_UNKNOWN AccountType = 0 // Unknown type, usually used as the default value
	AccountType_AccountType_ADMIN   AccountType = 1 // Full access permission, can manage all system resources and settings
	AccountType_AccountType_USER    AccountType = 2 // General user with access to basic functionalities only
	AccountType_AccountType_VENDOR  AccountType = 3 // Product provider with access to certain backend features for product
	// or order management
	AccountType_AccountType_STAFF AccountType = 4 // Operator with access to most resources but without administrator privileges
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "AccountType_UNKNOWN",
		1: "AccountType_ADMIN",
		2: "AccountType_USER",
		3: "AccountType_VENDOR",
		4: "AccountType_STAFF",
	}
	AccountType_value = map[string]int32{
		"AccountType_UNKNOWN": 0,
		"AccountType_ADMIN":   1,
		"AccountType_USER":    2,
		"AccountType_VENDOR":  3,
		"AccountType_STAFF":   4,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_identity_identity_proto_enumTypes[0].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_identity_identity_proto_enumTypes[0]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{0}
}

type AccountStatus int32

const (
	AccountStatus_AccountStatus_UNKNOWN AccountStatus = 0
	AccountStatus_AccountStatus_ENABLED AccountStatus = 1
	AccountStatus_AccountStatus_DELETED AccountStatus = 2
	AccountStatus_AccountStatus_BLOCKED AccountStatus = 3
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "AccountStatus_UNKNOWN",
		1: "AccountStatus_ENABLED",
		2: "AccountStatus_DELETED",
		3: "AccountStatus_BLOCKED",
	}
	AccountStatus_value = map[string]int32{
		"AccountStatus_UNKNOWN": 0,
		"AccountStatus_ENABLED": 1,
		"AccountStatus_DELETED": 2,
		"AccountStatus_BLOCKED": 3,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_identity_identity_proto_enumTypes[1].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_identity_identity_proto_enumTypes[1]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{1}
}

type VerificationResponse_VeriResult int32

const (
	VerificationResponse_Ok             VerificationResponse_VeriResult = 0
	VerificationResponse_TokenError     VerificationResponse_VeriResult = 1
	VerificationResponse_NoAccount      VerificationResponse_VeriResult = 2
	VerificationResponse_Verified       VerificationResponse_VeriResult = 3
	VerificationResponse_AccountFreezed VerificationResponse_VeriResult = 4
	VerificationResponse_InternalError  VerificationResponse_VeriResult = 5
)

// Enum value maps for VerificationResponse_VeriResult.
var (
	VerificationResponse_VeriResult_name = map[int32]string{
		0: "Ok",
		1: "TokenError",
		2: "NoAccount",
		3: "Verified",
		4: "AccountFreezed",
		5: "InternalError",
	}
	VerificationResponse_VeriResult_value = map[string]int32{
		"Ok":             0,
		"TokenError":     1,
		"NoAccount":      2,
		"Verified":       3,
		"AccountFreezed": 4,
		"InternalError":  5,
	}
)

func (x VerificationResponse_VeriResult) Enum() *VerificationResponse_VeriResult {
	p := new(VerificationResponse_VeriResult)
	*p = x
	return p
}

func (x VerificationResponse_VeriResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerificationResponse_VeriResult) Descriptor() protoreflect.EnumDescriptor {
	return file_identity_identity_proto_enumTypes[2].Descriptor()
}

func (VerificationResponse_VeriResult) Type() protoreflect.EnumType {
	return &file_identity_identity_proto_enumTypes[2]
}

func (x VerificationResponse_VeriResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerificationResponse_VeriResult.Descriptor instead.
func (VerificationResponse_VeriResult) EnumDescriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{16, 0}
}

// request
type RegisterAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Permission    *Permission            `protobuf:"bytes,4,opt,name=permission,proto3" json:"permission,omitempty"` // 權限
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAccountRequest) Reset() {
	*x = RegisterAccountRequest{}
	mi := &file_identity_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAccountRequest) ProtoMessage() {}

func (x *RegisterAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAccountRequest.ProtoReflect.Descriptor instead.
func (*RegisterAccountRequest) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterAccountRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RegisterAccountRequest) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type EmailVerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailVerificationRequest) Reset() {
	*x = EmailVerificationRequest{}
	mi := &file_identity_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailVerificationRequest) ProtoMessage() {}

func (x *EmailVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailVerificationRequest.ProtoReflect.Descriptor instead.
func (*EmailVerificationRequest) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{1}
}

func (x *EmailVerificationRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *EmailVerificationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailVerificationRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type SetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	By            string                 `protobuf:"bytes,1,opt,name=by,proto3" json:"by,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	OldPassword   string                 `protobuf:"bytes,4,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Code          string                 `protobuf:"bytes,7,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPasswordRequest) Reset() {
	*x = SetPasswordRequest{}
	mi := &file_identity_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPasswordRequest) ProtoMessage() {}

func (x *SetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPasswordRequest.ProtoReflect.Descriptor instead.
func (*SetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{2}
}

func (x *SetPasswordRequest) GetBy() string {
	if x != nil {
		return x.By
	}
	return ""
}

func (x *SetPasswordRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SetPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SetPasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *SetPasswordRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SetPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SetPasswordRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type DeleteOneAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOneAccountRequest) Reset() {
	*x = DeleteOneAccountRequest{}
	mi := &file_identity_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOneAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOneAccountRequest) ProtoMessage() {}

func (x *DeleteOneAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOneAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteOneAccountRequest) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteOneAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetOneAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneAccountRequest) Reset() {
	*x = GetOneAccountRequest{}
	mi := &file_identity_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneAccountRequest) ProtoMessage() {}

func (x *GetOneAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneAccountRequest.ProtoReflect.Descriptor instead.
func (*GetOneAccountRequest) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{4}
}

func (x *GetOneAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAllAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	By            string                 `protobuf:"bytes,1,opt,name=by,proto3" json:"by,omitempty"`
	Sort          string                 `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Perpage       uint32                 `protobuf:"varint,4,opt,name=perpage,proto3" json:"perpage,omitempty"`
	Filter        string                 `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	UserIds       []string               `protobuf:"bytes,6,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	AccountTypes  []AccountType          `protobuf:"varint,7,rep,packed,name=account_types,json=accountTypes,proto3,enum=identity.AccountType" json:"account_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAccountRequest) Reset() {
	*x = GetAllAccountRequest{}
	mi := &file_identity_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAccountRequest) ProtoMessage() {}

func (x *GetAllAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAllAccountRequest) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllAccountRequest) GetBy() string {
	if x != nil {
		return x.By
	}
	return ""
}

func (x *GetAllAccountRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *GetAllAccountRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllAccountRequest) GetPerpage() uint32 {
	if x != nil {
		return x.Perpage
	}
	return 0
}

func (x *GetAllAccountRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *GetAllAccountRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *GetAllAccountRequest) GetAccountTypes() []AccountType {
	if x != nil {
		return x.AccountTypes
	}
	return nil
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_identity_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{6}
}

func (x *GetProfileRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type UpdateProfileRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AccountId string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// profile
	UserName        string     `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Icon            []byte     `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Description     string     `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Gender          string     `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthday        *Date      `protobuf:"bytes,6,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Job             string     `protobuf:"bytes,7,opt,name=job,proto3" json:"job,omitempty"`
	Country         string     `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`
	City            string     `protobuf:"bytes,9,opt,name=city,proto3" json:"city,omitempty"`
	District        string     `protobuf:"bytes,15,opt,name=district,proto3" json:"district,omitempty"`
	ZipCode         string     `protobuf:"bytes,16,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Address         string     `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	ShippingAddress []*Adderss `protobuf:"bytes,11,rep,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	// personal setting
	Language      string          `protobuf:"bytes,12,opt,name=language,proto3" json:"language,omitempty"`
	EmailNoti     common.BoolType `protobuf:"varint,13,opt,name=email_noti,json=emailNoti,proto3,enum=common.BoolType" json:"email_noti,omitempty"`
	PhoneNoti     common.BoolType `protobuf:"varint,14,opt,name=phone_noti,json=phoneNoti,proto3,enum=common.BoolType" json:"phone_noti,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_identity_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProfileRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateProfileRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UpdateProfileRequest) GetIcon() []byte {
	if x != nil {
		return x.Icon
	}
	return nil
}

func (x *UpdateProfileRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProfileRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UpdateProfileRequest) GetBirthday() *Date {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *UpdateProfileRequest) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *UpdateProfileRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *UpdateProfileRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateProfileRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *UpdateProfileRequest) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *UpdateProfileRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateProfileRequest) GetShippingAddress() []*Adderss {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *UpdateProfileRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UpdateProfileRequest) GetEmailNoti() common.BoolType {
	if x != nil {
		return x.EmailNoti
	}
	return common.BoolType(0)
}

func (x *UpdateProfileRequest) GetPhoneNoti() common.BoolType {
	if x != nil {
		return x.PhoneNoti
	}
	return common.BoolType(0)
}

type ChangeContactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"` // email, phone
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeContactsRequest) Reset() {
	*x = ChangeContactsRequest{}
	mi := &file_identity_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeContactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeContactsRequest) ProtoMessage() {}

func (x *ChangeContactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeContactsRequest.ProtoReflect.Descriptor instead.
func (*ChangeContactsRequest) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{8}
}

func (x *ChangeContactsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ChangeContactsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ChangeContactsRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ChangeContactsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ModifyPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Permission    *Permission            `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyPermissionsRequest) Reset() {
	*x = ModifyPermissionsRequest{}
	mi := &file_identity_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyPermissionsRequest) ProtoMessage() {}

func (x *ModifyPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ModifyPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{9}
}

func (x *ModifyPermissionsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ModifyPermissionsRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ModifyPermissionsRequest) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type LoginAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    string                 `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	GrantType     string                 `protobuf:"bytes,2,opt,name=grant_type,json=grantType,proto3" json:"grant_type,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Code          string                 `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	ClientId      string                 `protobuf:"bytes,7,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,8,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginAccountRequest) Reset() {
	*x = LoginAccountRequest{}
	mi := &file_identity_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAccountRequest) ProtoMessage() {}

func (x *LoginAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAccountRequest.ProtoReflect.Descriptor instead.
func (*LoginAccountRequest) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{10}
}

func (x *LoginAccountRequest) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

func (x *LoginAccountRequest) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

func (x *LoginAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginAccountRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginAccountRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LoginAccountRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LoginAccountRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type CheckAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessTokenRequest) Reset() {
	*x = CheckAccessTokenRequest{}
	mi := &file_identity_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessTokenRequest) ProtoMessage() {}

func (x *CheckAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*CheckAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{11}
}

func (x *CheckAccessTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type SendVerificationCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    string                 `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendVerificationCodeRequest) Reset() {
	*x = SendVerificationCodeRequest{}
	mi := &file_identity_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVerificationCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVerificationCodeRequest) ProtoMessage() {}

func (x *SendVerificationCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVerificationCodeRequest.ProtoReflect.Descriptor instead.
func (*SendVerificationCodeRequest) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{12}
}

func (x *SendVerificationCodeRequest) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

func (x *SendVerificationCodeRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SendVerificationCodeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendVerificationCodeRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

// response
type RegisterAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Href          string                 `protobuf:"bytes,3,opt,name=href,proto3" json:"href,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAccountResponse) Reset() {
	*x = RegisterAccountResponse{}
	mi := &file_identity_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAccountResponse) ProtoMessage() {}

func (x *RegisterAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAccountResponse.ProtoReflect.Descriptor instead.
func (*RegisterAccountResponse) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterAccountResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterAccountResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RegisterAccountResponse) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

type LoginAccountResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountId       string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status          AccountStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=identity.AccountStatus" json:"status,omitempty"`
	AccessToken     string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken    string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType       string                 `protobuf:"bytes,5,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	TokenExpireIn   int64                  `protobuf:"varint,6,opt,name=token_expire_in,json=tokenExpireIn,proto3" json:"token_expire_in,omitempty"`
	RefreshExpireIn int64                  `protobuf:"varint,7,opt,name=refresh_expire_in,json=refreshExpireIn,proto3" json:"refresh_expire_in,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoginAccountResponse) Reset() {
	*x = LoginAccountResponse{}
	mi := &file_identity_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAccountResponse) ProtoMessage() {}

func (x *LoginAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAccountResponse.ProtoReflect.Descriptor instead.
func (*LoginAccountResponse) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{14}
}

func (x *LoginAccountResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *LoginAccountResponse) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_AccountStatus_UNKNOWN
}

func (x *LoginAccountResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginAccountResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginAccountResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *LoginAccountResponse) GetTokenExpireIn() int64 {
	if x != nil {
		return x.TokenExpireIn
	}
	return 0
}

func (x *LoginAccountResponse) GetRefreshExpireIn() int64 {
	if x != nil {
		return x.RefreshExpireIn
	}
	return 0
}

type GetAllAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.Pagination     `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Accounts      []*AccountInfo         `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAccountResponse) Reset() {
	*x = GetAllAccountResponse{}
	mi := &file_identity_identity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAccountResponse) ProtoMessage() {}

func (x *GetAllAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAllAccountResponse) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{15}
}

func (x *GetAllAccountResponse) GetMeta() *common.Pagination {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetAllAccountResponse) GetAccounts() []*AccountInfo {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type VerificationResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Result        VerificationResponse_VeriResult `protobuf:"varint,1,opt,name=result,proto3,enum=identity.VerificationResponse_VeriResult" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationResponse) Reset() {
	*x = VerificationResponse{}
	mi := &file_identity_identity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationResponse) ProtoMessage() {}

func (x *VerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationResponse.ProtoReflect.Descriptor instead.
func (*VerificationResponse) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{16}
}

func (x *VerificationResponse) GetResult() VerificationResponse_VeriResult {
	if x != nil {
		return x.Result
	}
	return VerificationResponse_Ok
}

type CheckAccessTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AccountType   AccountType            `protobuf:"varint,3,opt,name=account_type,json=accountType,proto3,enum=identity.AccountType" json:"account_type,omitempty"` // admin,user...etc
	RegisMode     string                 `protobuf:"bytes,4,opt,name=regis_mode,json=regisMode,proto3" json:"regis_mode,omitempty"`
	Status        AccountStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=identity.AccountStatus" json:"status,omitempty"` //
	EvStatus      bool                   `protobuf:"varint,6,opt,name=ev_status,json=evStatus,proto3" json:"ev_status,omitempty"`         // email 驗證狀態
	PvStatus      bool                   `protobuf:"varint,7,opt,name=pv_status,json=pvStatus,proto3" json:"pv_status,omitempty"`         // phone 驗證狀態
	Permission    *Permission            `protobuf:"bytes,8,opt,name=permission,proto3" json:"permission,omitempty"`                      // 權限
	Email         string                 `protobuf:"bytes,9,opt,name=email,proto3" json:"email,omitempty"`                                // user email
	Phone         string                 `protobuf:"bytes,10,opt,name=phone,proto3" json:"phone,omitempty"`                               // user phone (optional)
	EmailNoti     bool                   `protobuf:"varint,11,opt,name=email_noti,json=emailNoti,proto3" json:"email_noti,omitempty"`
	PhoneNoti     bool                   `protobuf:"varint,12,opt,name=phone_noti,json=phoneNoti,proto3" json:"phone_noti,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessTokenResponse) Reset() {
	*x = CheckAccessTokenResponse{}
	mi := &file_identity_identity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessTokenResponse) ProtoMessage() {}

func (x *CheckAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*CheckAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{17}
}

func (x *CheckAccessTokenResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CheckAccessTokenResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CheckAccessTokenResponse) GetAccountType() AccountType {
	if x != nil {
		return x.AccountType
	}
	return AccountType_AccountType_UNKNOWN
}

func (x *CheckAccessTokenResponse) GetRegisMode() string {
	if x != nil {
		return x.RegisMode
	}
	return ""
}

func (x *CheckAccessTokenResponse) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_AccountStatus_UNKNOWN
}

func (x *CheckAccessTokenResponse) GetEvStatus() bool {
	if x != nil {
		return x.EvStatus
	}
	return false
}

func (x *CheckAccessTokenResponse) GetPvStatus() bool {
	if x != nil {
		return x.PvStatus
	}
	return false
}

func (x *CheckAccessTokenResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

func (x *CheckAccessTokenResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CheckAccessTokenResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CheckAccessTokenResponse) GetEmailNoti() bool {
	if x != nil {
		return x.EmailNoti
	}
	return false
}

func (x *CheckAccessTokenResponse) GetPhoneNoti() bool {
	if x != nil {
		return x.PhoneNoti
	}
	return false
}

// model
type AccountInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AccountType   AccountType            `protobuf:"varint,3,opt,name=account_type,json=accountType,proto3,enum=identity.AccountType" json:"account_type,omitempty"`
	RegisMode     string                 `protobuf:"bytes,4,opt,name=regis_mode,json=regisMode,proto3" json:"regis_mode,omitempty"`
	Status        AccountStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=identity.AccountStatus" json:"status,omitempty"` //
	EvStatus      bool                   `protobuf:"varint,6,opt,name=ev_status,json=evStatus,proto3" json:"ev_status,omitempty"`         // email 驗證狀態
	PvStatus      bool                   `protobuf:"varint,7,opt,name=pv_status,json=pvStatus,proto3" json:"pv_status,omitempty"`         // phone 驗證狀態
	Permission    *Permission            `protobuf:"bytes,8,opt,name=permission,proto3" json:"permission,omitempty"`                      // 權限
	Password      string                 `protobuf:"bytes,9,opt,name=password,proto3" json:"password,omitempty"`                          // user password
	Email         string                 `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`                               // user email
	Phone         string                 `protobuf:"bytes,11,opt,name=phone,proto3" json:"phone,omitempty"`
	LoginAt       int64                  `protobuf:"varint,12,opt,name=login_at,json=loginAt,proto3" json:"login_at,omitempty"`       // timestamp ms
	LogoutAt      int64                  `protobuf:"varint,13,opt,name=logout_at,json=logoutAt,proto3" json:"logout_at,omitempty"`    // timestamp ms
	CreatedAt     int64                  `protobuf:"varint,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // timestamp ms
	UpdatedAt     int64                  `protobuf:"varint,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // timestamp ms
	DeletedAt     int64                  `protobuf:"varint,16,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"` // timestamp ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	mi := &file_identity_identity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{18}
}

func (x *AccountInfo) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountInfo) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AccountInfo) GetAccountType() AccountType {
	if x != nil {
		return x.AccountType
	}
	return AccountType_AccountType_UNKNOWN
}

func (x *AccountInfo) GetRegisMode() string {
	if x != nil {
		return x.RegisMode
	}
	return ""
}

func (x *AccountInfo) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_AccountStatus_UNKNOWN
}

func (x *AccountInfo) GetEvStatus() bool {
	if x != nil {
		return x.EvStatus
	}
	return false
}

func (x *AccountInfo) GetPvStatus() bool {
	if x != nil {
		return x.PvStatus
	}
	return false
}

func (x *AccountInfo) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

func (x *AccountInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AccountInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AccountInfo) GetLoginAt() int64 {
	if x != nil {
		return x.LoginAt
	}
	return 0
}

func (x *AccountInfo) GetLogoutAt() int64 {
	if x != nil {
		return x.LogoutAt
	}
	return 0
}

func (x *AccountInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AccountInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *AccountInfo) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type UserProfile struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AccountId string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// profile
	UserName        string     `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Icon            []byte     `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Description     string     `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Gender          string     `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthday        *Date      `protobuf:"bytes,6,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Job             string     `protobuf:"bytes,7,opt,name=job,proto3" json:"job,omitempty"`
	Country         string     `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`
	City            string     `protobuf:"bytes,9,opt,name=city,proto3" json:"city,omitempty"`
	District        string     `protobuf:"bytes,18,opt,name=district,proto3" json:"district,omitempty"`
	ZipCode         string     `protobuf:"bytes,19,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Address         string     `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	ShippingAddress []*Adderss `protobuf:"bytes,11,rep,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	// personal setting
	Language      string `protobuf:"bytes,12,opt,name=language,proto3" json:"language,omitempty"`
	EmailNoti     bool   `protobuf:"varint,13,opt,name=email_noti,json=emailNoti,proto3" json:"email_noti,omitempty"`
	PhoneNoti     bool   `protobuf:"varint,14,opt,name=phone_noti,json=phoneNoti,proto3" json:"phone_noti,omitempty"`
	CreatedAt     int64  `protobuf:"varint,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // timestamp ms
	UpdatedAt     int64  `protobuf:"varint,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // timestamp ms
	DeletedAt     int64  `protobuf:"varint,17,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"` // timestamp ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_identity_identity_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{19}
}

func (x *UserProfile) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UserProfile) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserProfile) GetIcon() []byte {
	if x != nil {
		return x.Icon
	}
	return nil
}

func (x *UserProfile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UserProfile) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UserProfile) GetBirthday() *Date {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *UserProfile) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *UserProfile) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *UserProfile) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UserProfile) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *UserProfile) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *UserProfile) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UserProfile) GetShippingAddress() []*Adderss {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *UserProfile) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UserProfile) GetEmailNoti() bool {
	if x != nil {
		return x.EmailNoti
	}
	return false
}

func (x *UserProfile) GetPhoneNoti() bool {
	if x != nil {
		return x.PhoneNoti
	}
	return false
}

func (x *UserProfile) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserProfile) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *UserProfile) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type Date struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           int32                  `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Date) Reset() {
	*x = Date{}
	mi := &file_identity_identity_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Date.ProtoReflect.Descriptor instead.
func (*Date) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{20}
}

func (x *Date) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *Date) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *Date) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type Permission struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	CanAccessCrossAccount     bool                   `protobuf:"varint,7,opt,name=can_access_cross_account,json=canAccessCrossAccount,proto3" json:"can_access_cross_account,omitempty"`             // Allow managing or viewing resources across accounts
	CanReadProduct            bool                   `protobuf:"varint,1,opt,name=can_read_product,json=canReadProduct,proto3" json:"can_read_product,omitempty"`                                    // View product details
	CanModifyProduct          bool                   `protobuf:"varint,2,opt,name=can_modify_product,json=canModifyProduct,proto3" json:"can_modify_product,omitempty"`                              // Create, update, or delete products
	CanReadOrder              bool                   `protobuf:"varint,3,opt,name=can_read_order,json=canReadOrder,proto3" json:"can_read_order,omitempty"`                                          // View order details
	CanModifyOrder            bool                   `protobuf:"varint,4,opt,name=can_modify_order,json=canModifyOrder,proto3" json:"can_modify_order,omitempty"`                                    // Create, update, or cancel orders
	CanReceiveEmails          bool                   `protobuf:"varint,5,opt,name=can_receive_emails,json=canReceiveEmails,proto3" json:"can_receive_emails,omitempty"`                              // Subscribe to promotional or notification emails
	CanParticipateInMarketing bool                   `protobuf:"varint,6,opt,name=can_participate_in_marketing,json=canParticipateInMarketing,proto3" json:"can_participate_in_marketing,omitempty"` // Participate in joint marketing campaigns
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_identity_identity_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{21}
}

func (x *Permission) GetCanAccessCrossAccount() bool {
	if x != nil {
		return x.CanAccessCrossAccount
	}
	return false
}

func (x *Permission) GetCanReadProduct() bool {
	if x != nil {
		return x.CanReadProduct
	}
	return false
}

func (x *Permission) GetCanModifyProduct() bool {
	if x != nil {
		return x.CanModifyProduct
	}
	return false
}

func (x *Permission) GetCanReadOrder() bool {
	if x != nil {
		return x.CanReadOrder
	}
	return false
}

func (x *Permission) GetCanModifyOrder() bool {
	if x != nil {
		return x.CanModifyOrder
	}
	return false
}

func (x *Permission) GetCanReceiveEmails() bool {
	if x != nil {
		return x.CanReceiveEmails
	}
	return false
}

func (x *Permission) GetCanParticipateInMarketing() bool {
	if x != nil {
		return x.CanParticipateInMarketing
	}
	return false
}

type Adderss struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // 宅配、超商(711.全家...etc)
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,5,opt,name=district,proto3" json:"district,omitempty"`
	ZipCode       string                 `protobuf:"bytes,6,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	StoreId       string                 `protobuf:"bytes,7,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Adderss) Reset() {
	*x = Adderss{}
	mi := &file_identity_identity_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Adderss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Adderss) ProtoMessage() {}

func (x *Adderss) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Adderss.ProtoReflect.Descriptor instead.
func (*Adderss) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{22}
}

func (x *Adderss) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Adderss) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Adderss) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Adderss) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *Adderss) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *Adderss) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Adderss) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type ListProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountIds    []string               `protobuf:"bytes,1,rep,name=account_ids,json=accountIds,proto3" json:"account_ids,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Perpage       uint32                 `protobuf:"varint,3,opt,name=perpage,proto3" json:"perpage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_identity_identity_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{23}
}

func (x *ListProfilesRequest) GetAccountIds() []string {
	if x != nil {
		return x.AccountIds
	}
	return nil
}

func (x *ListProfilesRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProfilesRequest) GetPerpage() uint32 {
	if x != nil {
		return x.Perpage
	}
	return 0
}

type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *common.Pagination     `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Profiles      []*UserProfile         `protobuf:"bytes,2,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_identity_identity_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{24}
}

func (x *ListProfilesResponse) GetMeta() *common.Pagination {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ListProfilesResponse) GetProfiles() []*UserProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type ReFreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReFreshTokenRequest) Reset() {
	*x = ReFreshTokenRequest{}
	mi := &file_identity_identity_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReFreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReFreshTokenRequest) ProtoMessage() {}

func (x *ReFreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReFreshTokenRequest.ProtoReflect.Descriptor instead.
func (*ReFreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{25}
}

func (x *ReFreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ReFreshTokenResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountId       string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccessToken     string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken    string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType       string                 `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	TokenExpireIn   int64                  `protobuf:"varint,5,opt,name=token_expire_in,json=tokenExpireIn,proto3" json:"token_expire_in,omitempty"`
	RefreshExpireIn int64                  `protobuf:"varint,6,opt,name=refresh_expire_in,json=refreshExpireIn,proto3" json:"refresh_expire_in,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReFreshTokenResponse) Reset() {
	*x = ReFreshTokenResponse{}
	mi := &file_identity_identity_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReFreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReFreshTokenResponse) ProtoMessage() {}

func (x *ReFreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReFreshTokenResponse.ProtoReflect.Descriptor instead.
func (*ReFreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{26}
}

func (x *ReFreshTokenResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ReFreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ReFreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *ReFreshTokenResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *ReFreshTokenResponse) GetTokenExpireIn() int64 {
	if x != nil {
		return x.TokenExpireIn
	}
	return 0
}

func (x *ReFreshTokenResponse) GetRefreshExpireIn() int64 {
	if x != nil {
		return x.RefreshExpireIn
	}
	return 0
}

type SetAccountBlockStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	IsBlocked     bool                   `protobuf:"varint,2,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAccountBlockStatusRequest) Reset() {
	*x = SetAccountBlockStatusRequest{}
	mi := &file_identity_identity_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAccountBlockStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAccountBlockStatusRequest) ProtoMessage() {}

func (x *SetAccountBlockStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAccountBlockStatusRequest.ProtoReflect.Descriptor instead.
func (*SetAccountBlockStatusRequest) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{27}
}

func (x *SetAccountBlockStatusRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SetAccountBlockStatusRequest) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AccountType   AccountType            `protobuf:"varint,2,opt,name=account_type,json=accountType,proto3,enum=identity.AccountType" json:"account_type,omitempty"`
	RegisMode     string                 `protobuf:"bytes,3,opt,name=regis_mode,json=regisMode,proto3" json:"regis_mode,omitempty"`
	Status        AccountStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=identity.AccountStatus" json:"status,omitempty"` //
	Permission    *Permission            `protobuf:"bytes,5,opt,name=permission,proto3" json:"permission,omitempty"`                      // 權限
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`                          // user password
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`                                // user email
	Phone         string                 `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	UserName      string                 `protobuf:"bytes,9,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Gender        string                 `protobuf:"bytes,10,opt,name=gender,proto3" json:"gender,omitempty"`
	EmailNoti     common.BoolType        `protobuf:"varint,11,opt,name=email_noti,json=emailNoti,proto3,enum=common.BoolType" json:"email_noti,omitempty"`
	PhoneNoti     common.BoolType        `protobuf:"varint,12,opt,name=phone_noti,json=phoneNoti,proto3,enum=common.BoolType" json:"phone_noti,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_identity_identity_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{28}
}

func (x *CreateAccountRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CreateAccountRequest) GetAccountType() AccountType {
	if x != nil {
		return x.AccountType
	}
	return AccountType_AccountType_UNKNOWN
}

func (x *CreateAccountRequest) GetRegisMode() string {
	if x != nil {
		return x.RegisMode
	}
	return ""
}

func (x *CreateAccountRequest) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_AccountStatus_UNKNOWN
}

func (x *CreateAccountRequest) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

func (x *CreateAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAccountRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateAccountRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateAccountRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreateAccountRequest) GetEmailNoti() common.BoolType {
	if x != nil {
		return x.EmailNoti
	}
	return common.BoolType(0)
}

func (x *CreateAccountRequest) GetPhoneNoti() common.BoolType {
	if x != nil {
		return x.PhoneNoti
	}
	return common.BoolType(0)
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountType   AccountType            `protobuf:"varint,2,opt,name=account_type,json=accountType,proto3,enum=identity.AccountType" json:"account_type,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"` // user email
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_identity_identity_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_identity_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_identity_identity_proto_rawDescGZIP(), []int{29}
}

func (x *CreateAccountResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateAccountResponse) GetAccountType() AccountType {
	if x != nil {
		return x.AccountType
	}
	return AccountType_AccountType_UNKNOWN
}

func (x *CreateAccountResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_identity_identity_proto protoreflect.FileDescriptor

const file_identity_identity_proto_rawDesc = "" +
	"\n" +
	"\x17identity/identity.proto\x12\bidentity\x1a\x17common/pagination.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x11common/type.proto\"\x9d\x01\n" +
	"\x16RegisterAccountRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x124\n" +
	"\n" +
	"permission\x18\x04 \x01(\v2\x14.identity.PermissionR\n" +
	"permission\"g\n" +
	"\x18EmailVerificationRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"\xc6\x01\n" +
	"\x12SetPasswordRequest\x12\x0e\n" +
	"\x02by\x18\x01 \x01(\tR\x02by\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12!\n" +
	"\fold_password\x18\x04 \x01(\tR\voldPassword\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\a \x01(\tR\x04code\"8\n" +
	"\x17DeleteOneAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"5\n" +
	"\x14GetOneAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\xd7\x01\n" +
	"\x14GetAllAccountRequest\x12\x0e\n" +
	"\x02by\x18\x01 \x01(\tR\x02by\x12\x12\n" +
	"\x04sort\x18\x02 \x01(\tR\x04sort\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x18\n" +
	"\aperpage\x18\x04 \x01(\rR\aperpage\x12\x16\n" +
	"\x06filter\x18\x05 \x01(\tR\x06filter\x12\x19\n" +
	"\buser_ids\x18\x06 \x03(\tR\auserIds\x12:\n" +
	"\raccount_types\x18\a \x03(\x0e2\x15.identity.AccountTypeR\faccountTypes\"2\n" +
	"\x11GetProfileRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\x99\x04\n" +
	"\x14UpdateProfileRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\fR\x04icon\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12*\n" +
	"\bbirthday\x18\x06 \x01(\v2\x0e.identity.DateR\bbirthday\x12\x10\n" +
	"\x03job\x18\a \x01(\tR\x03job\x12\x18\n" +
	"\acountry\x18\b \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\t \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\x0f \x01(\tR\bdistrict\x12\x19\n" +
	"\bzip_code\x18\x10 \x01(\tR\azipCode\x12\x18\n" +
	"\aaddress\x18\n" +
	" \x01(\tR\aaddress\x12<\n" +
	"\x10shipping_address\x18\v \x03(\v2\x11.identity.AdderssR\x0fshippingAddress\x12\x1a\n" +
	"\blanguage\x18\f \x01(\tR\blanguage\x12/\n" +
	"\n" +
	"email_noti\x18\r \x01(\x0e2\x10.common.BoolTypeR\temailNoti\x12/\n" +
	"\n" +
	"phone_noti\x18\x0e \x01(\x0e2\x10.common.BoolTypeR\tphoneNoti\"~\n" +
	"\x15ChangeContactsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\"\x8c\x01\n" +
	"\x18ModifyPermissionsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x124\n" +
	"\n" +
	"permission\x18\x03 \x01(\v2\x14.identity.PermissionR\n" +
	"permission\"\xf2\x01\n" +
	"\x13LoginAccountRequest\x12\x1e\n" +
	"\n" +
	"connection\x18\x01 \x01(\tR\n" +
	"connection\x12\x1d\n" +
	"\n" +
	"grant_type\x18\x02 \x01(\tR\tgrantType\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x12\n" +
	"\x04code\x18\x06 \x01(\tR\x04code\x12\x1b\n" +
	"\tclient_id\x18\a \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\b \x01(\tR\fclientSecret\"<\n" +
	"\x17CheckAccessTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\x81\x01\n" +
	"\x1bSendVerificationCodeRequest\x12\x1e\n" +
	"\n" +
	"connection\x18\x01 \x01(\tR\n" +
	"connection\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\"`\n" +
	"\x17RegisterAccountResponse\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x12\n" +
	"\x04href\x18\x03 \x01(\tR\x04href\"\xa1\x02\n" +
	"\x14LoginAccountResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.identity.AccountStatusR\x06status\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x05 \x01(\tR\ttokenType\x12&\n" +
	"\x0ftoken_expire_in\x18\x06 \x01(\x03R\rtokenExpireIn\x12*\n" +
	"\x11refresh_expire_in\x18\a \x01(\x03R\x0frefreshExpireIn\"r\n" +
	"\x15GetAllAccountResponse\x12&\n" +
	"\x04meta\x18\x01 \x01(\v2\x12.common.PaginationR\x04meta\x121\n" +
	"\baccounts\x18\x02 \x03(\v2\x15.identity.AccountInfoR\baccounts\"\xc3\x01\n" +
	"\x14VerificationResponse\x12A\n" +
	"\x06result\x18\x01 \x01(\x0e2).identity.VerificationResponse.VeriResultR\x06result\"h\n" +
	"\n" +
	"VeriResult\x12\x06\n" +
	"\x02Ok\x10\x00\x12\x0e\n" +
	"\n" +
	"TokenError\x10\x01\x12\r\n" +
	"\tNoAccount\x10\x02\x12\f\n" +
	"\bVerified\x10\x03\x12\x12\n" +
	"\x0eAccountFreezed\x10\x04\x12\x11\n" +
	"\rInternalError\x10\x05\"\xb4\x03\n" +
	"\x18CheckAccessTokenResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x128\n" +
	"\faccount_type\x18\x03 \x01(\x0e2\x15.identity.AccountTypeR\vaccountType\x12\x1d\n" +
	"\n" +
	"regis_mode\x18\x04 \x01(\tR\tregisMode\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.identity.AccountStatusR\x06status\x12\x1b\n" +
	"\tev_status\x18\x06 \x01(\bR\bevStatus\x12\x1b\n" +
	"\tpv_status\x18\a \x01(\bR\bpvStatus\x124\n" +
	"\n" +
	"permission\x18\b \x01(\v2\x14.identity.PermissionR\n" +
	"permission\x12\x14\n" +
	"\x05email\x18\t \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\n" +
	" \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"email_noti\x18\v \x01(\bR\temailNoti\x12\x1d\n" +
	"\n" +
	"phone_noti\x18\f \x01(\bR\tphoneNoti\"\x9a\x04\n" +
	"\vAccountInfo\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x128\n" +
	"\faccount_type\x18\x03 \x01(\x0e2\x15.identity.AccountTypeR\vaccountType\x12\x1d\n" +
	"\n" +
	"regis_mode\x18\x04 \x01(\tR\tregisMode\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.identity.AccountStatusR\x06status\x12\x1b\n" +
	"\tev_status\x18\x06 \x01(\bR\bevStatus\x12\x1b\n" +
	"\tpv_status\x18\a \x01(\bR\bpvStatus\x124\n" +
	"\n" +
	"permission\x18\b \x01(\v2\x14.identity.PermissionR\n" +
	"permission\x12\x1a\n" +
	"\bpassword\x18\t \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\n" +
	" \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\v \x01(\tR\x05phone\x12\x19\n" +
	"\blogin_at\x18\f \x01(\x03R\aloginAt\x12\x1b\n" +
	"\tlogout_at\x18\r \x01(\x03R\blogoutAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\x10 \x01(\x03R\tdeletedAt\"\xc9\x04\n" +
	"\vUserProfile\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\fR\x04icon\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12*\n" +
	"\bbirthday\x18\x06 \x01(\v2\x0e.identity.DateR\bbirthday\x12\x10\n" +
	"\x03job\x18\a \x01(\tR\x03job\x12\x18\n" +
	"\acountry\x18\b \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\t \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\x12 \x01(\tR\bdistrict\x12\x19\n" +
	"\bzip_code\x18\x13 \x01(\tR\azipCode\x12\x18\n" +
	"\aaddress\x18\n" +
	" \x01(\tR\aaddress\x12<\n" +
	"\x10shipping_address\x18\v \x03(\v2\x11.identity.AdderssR\x0fshippingAddress\x12\x1a\n" +
	"\blanguage\x18\f \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"email_noti\x18\r \x01(\bR\temailNoti\x12\x1d\n" +
	"\n" +
	"phone_noti\x18\x0e \x01(\bR\tphoneNoti\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\x11 \x01(\x03R\tdeletedAt\"B\n" +
	"\x04Date\x12\x10\n" +
	"\x03day\x18\x01 \x01(\x05R\x03day\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\"\xdc\x02\n" +
	"\n" +
	"Permission\x127\n" +
	"\x18can_access_cross_account\x18\a \x01(\bR\x15canAccessCrossAccount\x12(\n" +
	"\x10can_read_product\x18\x01 \x01(\bR\x0ecanReadProduct\x12,\n" +
	"\x12can_modify_product\x18\x02 \x01(\bR\x10canModifyProduct\x12$\n" +
	"\x0ecan_read_order\x18\x03 \x01(\bR\fcanReadOrder\x12(\n" +
	"\x10can_modify_order\x18\x04 \x01(\bR\x0ecanModifyOrder\x12,\n" +
	"\x12can_receive_emails\x18\x05 \x01(\bR\x10canReceiveEmails\x12?\n" +
	"\x1ccan_participate_in_marketing\x18\x06 \x01(\bR\x19canParticipateInMarketing\"\xb7\x01\n" +
	"\aAdderss\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\x05 \x01(\tR\bdistrict\x12\x19\n" +
	"\bzip_code\x18\x06 \x01(\tR\azipCode\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x19\n" +
	"\bstore_id\x18\a \x01(\tR\astoreId\"d\n" +
	"\x13ListProfilesRequest\x12\x1f\n" +
	"\vaccount_ids\x18\x01 \x03(\tR\n" +
	"accountIds\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x18\n" +
	"\aperpage\x18\x03 \x01(\rR\aperpage\"q\n" +
	"\x14ListProfilesResponse\x12&\n" +
	"\x04meta\x18\x01 \x01(\v2\x12.common.PaginationR\x04meta\x121\n" +
	"\bprofiles\x18\x02 \x03(\v2\x15.identity.UserProfileR\bprofiles\":\n" +
	"\x13ReFreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\xf0\x01\n" +
	"\x14ReFreshTokenResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\x12&\n" +
	"\x0ftoken_expire_in\x18\x05 \x01(\x03R\rtokenExpireIn\x12*\n" +
	"\x11refresh_expire_in\x18\x06 \x01(\x03R\x0frefreshExpireIn\"\\\n" +
	"\x1cSetAccountBlockStatusRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1d\n" +
	"\n" +
	"is_blocked\x18\x02 \x01(\bR\tisBlocked\"\xcc\x03\n" +
	"\x14CreateAccountRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x128\n" +
	"\faccount_type\x18\x02 \x01(\x0e2\x15.identity.AccountTypeR\vaccountType\x12\x1d\n" +
	"\n" +
	"regis_mode\x18\x03 \x01(\tR\tregisMode\x12/\n" +
	"\x06status\x18\x04 \x01(\x0e2\x17.identity.AccountStatusR\x06status\x124\n" +
	"\n" +
	"permission\x18\x05 \x01(\v2\x14.identity.PermissionR\n" +
	"permission\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\b \x01(\tR\x05phone\x12\x1b\n" +
	"\tuser_name\x18\t \x01(\tR\buserName\x12\x16\n" +
	"\x06gender\x18\n" +
	" \x01(\tR\x06gender\x12/\n" +
	"\n" +
	"email_noti\x18\v \x01(\x0e2\x10.common.BoolTypeR\temailNoti\x12/\n" +
	"\n" +
	"phone_noti\x18\f \x01(\x0e2\x10.common.BoolTypeR\tphoneNoti\"\x86\x01\n" +
	"\x15CreateAccountResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x128\n" +
	"\faccount_type\x18\x02 \x01(\x0e2\x15.identity.AccountTypeR\vaccountType\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email*\x82\x01\n" +
	"\vAccountType\x12\x17\n" +
	"\x13AccountType_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11AccountType_ADMIN\x10\x01\x12\x14\n" +
	"\x10AccountType_USER\x10\x02\x12\x16\n" +
	"\x12AccountType_VENDOR\x10\x03\x12\x15\n" +
	"\x11AccountType_STAFF\x10\x04*{\n" +
	"\rAccountStatus\x12\x19\n" +
	"\x15AccountStatus_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15AccountStatus_ENABLED\x10\x01\x12\x19\n" +
	"\x15AccountStatus_DELETED\x10\x02\x12\x19\n" +
	"\x15AccountStatus_BLOCKED\x10\x032\xbb\x01\n" +
	"\x0fIdentityService\x12V\n" +
	"\x0fRegisterAccount\x12 .identity.RegisterAccountRequest\x1a!.identity.RegisterAccountResponse\x12P\n" +
	"\rCreateAccount\x12\x1e.identity.CreateAccountRequest\x1a\x1f.identity.CreateAccountResponseB9Z7github.com/chise0904/golang_template/proto/pkg/identityb\x06proto3"

var (
	file_identity_identity_proto_rawDescOnce sync.Once
	file_identity_identity_proto_rawDescData []byte
)

func file_identity_identity_proto_rawDescGZIP() []byte {
	file_identity_identity_proto_rawDescOnce.Do(func() {
		file_identity_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_identity_proto_rawDesc), len(file_identity_identity_proto_rawDesc)))
	})
	return file_identity_identity_proto_rawDescData
}

var file_identity_identity_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_identity_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_identity_identity_proto_goTypes = []any{
	(AccountType)(0),                     // 0: identity.AccountType
	(AccountStatus)(0),                   // 1: identity.AccountStatus
	(VerificationResponse_VeriResult)(0), // 2: identity.VerificationResponse.VeriResult
	(*RegisterAccountRequest)(nil),       // 3: identity.RegisterAccountRequest
	(*EmailVerificationRequest)(nil),     // 4: identity.EmailVerificationRequest
	(*SetPasswordRequest)(nil),           // 5: identity.SetPasswordRequest
	(*DeleteOneAccountRequest)(nil),      // 6: identity.DeleteOneAccountRequest
	(*GetOneAccountRequest)(nil),         // 7: identity.GetOneAccountRequest
	(*GetAllAccountRequest)(nil),         // 8: identity.GetAllAccountRequest
	(*GetProfileRequest)(nil),            // 9: identity.GetProfileRequest
	(*UpdateProfileRequest)(nil),         // 10: identity.UpdateProfileRequest
	(*ChangeContactsRequest)(nil),        // 11: identity.ChangeContactsRequest
	(*ModifyPermissionsRequest)(nil),     // 12: identity.ModifyPermissionsRequest
	(*LoginAccountRequest)(nil),          // 13: identity.LoginAccountRequest
	(*CheckAccessTokenRequest)(nil),      // 14: identity.CheckAccessTokenRequest
	(*SendVerificationCodeRequest)(nil),  // 15: identity.SendVerificationCodeRequest
	(*RegisterAccountResponse)(nil),      // 16: identity.RegisterAccountResponse
	(*LoginAccountResponse)(nil),         // 17: identity.LoginAccountResponse
	(*GetAllAccountResponse)(nil),        // 18: identity.GetAllAccountResponse
	(*VerificationResponse)(nil),         // 19: identity.VerificationResponse
	(*CheckAccessTokenResponse)(nil),     // 20: identity.CheckAccessTokenResponse
	(*AccountInfo)(nil),                  // 21: identity.AccountInfo
	(*UserProfile)(nil),                  // 22: identity.UserProfile
	(*Date)(nil),                         // 23: identity.Date
	(*Permission)(nil),                   // 24: identity.Permission
	(*Adderss)(nil),                      // 25: identity.Adderss
	(*ListProfilesRequest)(nil),          // 26: identity.ListProfilesRequest
	(*ListProfilesResponse)(nil),         // 27: identity.ListProfilesResponse
	(*ReFreshTokenRequest)(nil),          // 28: identity.ReFreshTokenRequest
	(*ReFreshTokenResponse)(nil),         // 29: identity.ReFreshTokenResponse
	(*SetAccountBlockStatusRequest)(nil), // 30: identity.SetAccountBlockStatusRequest
	(*CreateAccountRequest)(nil),         // 31: identity.CreateAccountRequest
	(*CreateAccountResponse)(nil),        // 32: identity.CreateAccountResponse
	(common.BoolType)(0),                 // 33: common.BoolType
	(*common.Pagination)(nil),            // 34: common.Pagination
}
var file_identity_identity_proto_depIdxs = []int32{
	24, // 0: identity.RegisterAccountRequest.permission:type_name -> identity.Permission
	0,  // 1: identity.GetAllAccountRequest.account_types:type_name -> identity.AccountType
	23, // 2: identity.UpdateProfileRequest.birthday:type_name -> identity.Date
	25, // 3: identity.UpdateProfileRequest.shipping_address:type_name -> identity.Adderss
	33, // 4: identity.UpdateProfileRequest.email_noti:type_name -> common.BoolType
	33, // 5: identity.UpdateProfileRequest.phone_noti:type_name -> common.BoolType
	24, // 6: identity.ModifyPermissionsRequest.permission:type_name -> identity.Permission
	1,  // 7: identity.LoginAccountResponse.status:type_name -> identity.AccountStatus
	34, // 8: identity.GetAllAccountResponse.meta:type_name -> common.Pagination
	21, // 9: identity.GetAllAccountResponse.accounts:type_name -> identity.AccountInfo
	2,  // 10: identity.VerificationResponse.result:type_name -> identity.VerificationResponse.VeriResult
	0,  // 11: identity.CheckAccessTokenResponse.account_type:type_name -> identity.AccountType
	1,  // 12: identity.CheckAccessTokenResponse.status:type_name -> identity.AccountStatus
	24, // 13: identity.CheckAccessTokenResponse.permission:type_name -> identity.Permission
	0,  // 14: identity.AccountInfo.account_type:type_name -> identity.AccountType
	1,  // 15: identity.AccountInfo.status:type_name -> identity.AccountStatus
	24, // 16: identity.AccountInfo.permission:type_name -> identity.Permission
	23, // 17: identity.UserProfile.birthday:type_name -> identity.Date
	25, // 18: identity.UserProfile.shipping_address:type_name -> identity.Adderss
	34, // 19: identity.ListProfilesResponse.meta:type_name -> common.Pagination
	22, // 20: identity.ListProfilesResponse.profiles:type_name -> identity.UserProfile
	0,  // 21: identity.CreateAccountRequest.account_type:type_name -> identity.AccountType
	1,  // 22: identity.CreateAccountRequest.status:type_name -> identity.AccountStatus
	24, // 23: identity.CreateAccountRequest.permission:type_name -> identity.Permission
	33, // 24: identity.CreateAccountRequest.email_noti:type_name -> common.BoolType
	33, // 25: identity.CreateAccountRequest.phone_noti:type_name -> common.BoolType
	0,  // 26: identity.CreateAccountResponse.account_type:type_name -> identity.AccountType
	3,  // 27: identity.IdentityService.RegisterAccount:input_type -> identity.RegisterAccountRequest
	31, // 28: identity.IdentityService.CreateAccount:input_type -> identity.CreateAccountRequest
	16, // 29: identity.IdentityService.RegisterAccount:output_type -> identity.RegisterAccountResponse
	32, // 30: identity.IdentityService.CreateAccount:output_type -> identity.CreateAccountResponse
	29, // [29:31] is the sub-list for method output_type
	27, // [27:29] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_identity_identity_proto_init() }
func file_identity_identity_proto_init() {
	if File_identity_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_identity_proto_rawDesc), len(file_identity_identity_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_identity_proto_goTypes,
		DependencyIndexes: file_identity_identity_proto_depIdxs,
		EnumInfos:         file_identity_identity_proto_enumTypes,
		MessageInfos:      file_identity_identity_proto_msgTypes,
	}.Build()
	File_identity_identity_proto = out.File
	file_identity_identity_proto_goTypes = nil
	file_identity_identity_proto_depIdxs = nil
}
