// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: common/type.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoolType int32

const (
	BoolType_NoSet BoolType = 0
	BoolType_True  BoolType = 1
	BoolType_False BoolType = 2
)

// Enum value maps for BoolType.
var (
	BoolType_name = map[int32]string{
		0: "NoSet",
		1: "True",
		2: "False",
	}
	BoolType_value = map[string]int32{
		"NoSet": 0,
		"True":  1,
		"False": 2,
	}
)

func (x BoolType) Enum() *BoolType {
	p := new(BoolType)
	*p = x
	return p
}

func (x BoolType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BoolType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_type_proto_enumTypes[0].Descriptor()
}

func (BoolType) Type() protoreflect.EnumType {
	return &file_common_type_proto_enumTypes[0]
}

func (x BoolType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BoolType.Descriptor instead.
func (BoolType) EnumDescriptor() ([]byte, []int) {
	return file_common_type_proto_rawDescGZIP(), []int{0}
}

var File_common_type_proto protoreflect.FileDescriptor

const file_common_type_proto_rawDesc = "" +
	"\n" +
	"\x11common/type.proto\x12\x06common**\n" +
	"\bBoolType\x12\t\n" +
	"\x05NoSet\x10\x00\x12\b\n" +
	"\x04True\x10\x01\x12\t\n" +
	"\x05False\x10\x02B7Z5github.com/chise0904/golang_template/proto/pkg/commonb\x06proto3"

var (
	file_common_type_proto_rawDescOnce sync.Once
	file_common_type_proto_rawDescData []byte
)

func file_common_type_proto_rawDescGZIP() []byte {
	file_common_type_proto_rawDescOnce.Do(func() {
		file_common_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_type_proto_rawDesc), len(file_common_type_proto_rawDesc)))
	})
	return file_common_type_proto_rawDescData
}

var file_common_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_type_proto_goTypes = []any{
	(BoolType)(0), // 0: common.BoolType
}
var file_common_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_type_proto_init() }
func file_common_type_proto_init() {
	if File_common_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_type_proto_rawDesc), len(file_common_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_type_proto_goTypes,
		DependencyIndexes: file_common_type_proto_depIdxs,
		EnumInfos:         file_common_type_proto_enumTypes,
	}.Build()
	File_common_type_proto = out.File
	file_common_type_proto_goTypes = nil
	file_common_type_proto_depIdxs = nil
}
